steps:
- name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'asia.gcr.io/$PROJECT_ID/python:${SHORT_SHA}', './python' ]
  timeout: 1800s
images:
- 'asia.gcr.io/$PROJECT_ID/python:${SHORT_SHA}'
