version: 2
jobs:
  build:
    docker: 
    - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true
      - run: |
          echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
      - run: docker build -t asia.gcr.io/ongoing-236000/python ./python
      - run: docker push asia.gcr.io/ongoing-236000/python
