version: 2.1
executors:
  docker-publisher:
    docker: 
      - image: google/cloud-sdk

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t  python ./python
      - run: docker save -o image.tar python
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
            - ./auth_docker.sh

  publish-to-gcloud:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run:
          name: Debug image name
          command: echo $CIRCLE_BRANCH
      - run: 
          name: Authorise docker
          command: ./auth_docker.sh
      - run: 
          name: Load docker image
          command: docker load -i /tmp/workspace/image.tar
      - run: 
          name: Tag docker image
          command: docker tag python asia.gcr.io/ongoing-236000/python-$CIRCLE_BRANCH
      - run: 
          name: Push docker image
          command: docker push asia.gcr.io/ongoing-236000/python-$CIRCLE_BRANCH

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish-to-gcloud:
          requires:
            - build
          filters:
            branches:
              only: /^(master|develop)/
