version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: asia.gcr.io/ongoing-236000/python
    docker: 
      - image: google/cloud-sdk

jobs:
  build:
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true
      - run: ./auth_docker.sh
      # - run: |
          # echo $GCLOUD_SERVICE_KEY | gcloud auth activate-service-account --key-file=-
          # gcloud --quiet config set project ${GOOGLE_PROJECT_ID}
          # gcloud --quiet config set compute/zone ${GOOGLE_COMPUTE_ZONE}
          # gcloud auth configure-docker
      - run: docker build -t $IMAGE_NAME ./python
      - run: docker push $IMAGE_NAME
