version: 2.0

jobs:
  build:
    working_directory: /tmp/build
    docker: 
      - image: google/cloud-sdk
    steps:
      - checkout
      - setup_remote_docker
      - run: 
          name: Authorise docker
          command: ./auth_docker.sh
      - run:
          name: Build and push image
          command: ./build_push.sh
