version: 2.1
executors:
  docker-publisher:
    docker: 
      - image: google/cloud-sdk

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Build docker image
          command: docker build -t  python ./python
      - run: 
          name: Save docker image
          command: docker save -o image.tar python
      - persist_to_workspace:
          root: .
          paths:
            - ./image.tar
            - ./auth_docker.sh
            - ./push_docker.sh

  publish-to-gcloud:
    executor: docker-publisher
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - setup_remote_docker
      - run: 
          name: Authorise docker
          command: ./auth_docker.sh
      - run: 
          name: Push docker image
          command: ./push_docker.sh

workflows:
  version: 2
  build-deploy:
    jobs:
      - build
      - publish-to-gcloud:
          requires:
            - build
          filters:
            branches:
              only: /^(master|develop)/
