version: 2.1

executors:
  docker-publisher:
    environment:
      IMAGE_NAME: asia.gcr.io/ongoing-236000/python-$CIRCLE_BRANCH
    docker: 
      - image: google/cloud-sdk

jobs:
  build:
    executor: docker-publisher
    steps:
      - checkout
      - setup_remote_docker:   
          docker_layer_caching: true
      - run: docker build -t $IMAGE_NAME ./python
      - run: docker save -o image.tar $IMAGE_NAME
      - persist_to_workspace:
        root: .
        paths:
          - ./image.tar
  publish:
    executor: docker-publisher
    steps:
      - attach_workspace:
        at: /tmp/workspace
      - setup_remote_docker:
      - run: ./auth_docker.sh
      - run: docker load -i /tmp/workspace/image.tar
      - run: docker push $IMAGE_NAME
      
  workflows:
    version: 2
    build-deploy:
      jobs:
        - build:
        - publish-latest:
          requires:
            - build
          filters:
            branches:
              only: /^(master|develop)/
